/**
 * @manga/domain — Shared domain types for the Manga Infrastructure.
 *
 * These types represent the canonical content hierarchy:
 *   Series → Episode → Page → Panel → Bubble
 *
 * Source of truth: ARCHITECTURE.md §4, comic-domain-spec.md, schema.prisma
 *
 * Used by:
 *   - apps/viewer (public reader)
 *   - apps/cms (admin SPA)
 *   - apps/api (Hono API)
 */

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

export interface BoundingBox {
    x: number;
    y: number;
    width: number;
    height: number;
}

// ---------------------------------------------------------------------------
// Content hierarchy
// ---------------------------------------------------------------------------

export type BubbleType = "speech" | "thought" | "narration" | "sfx" | "caption" | "other";
export type TextDirection = "horizontal" | "vertical";
export type SpeakerConfidence = "confirmed" | "inferred" | "unknown";

export interface ContentFlags {
    shareable: boolean;
    feedback_enabled: boolean;
    contains_spoiler?: boolean;
}

export interface Bubble {
    id: string;
    bubbleNumber: number;
    shortId: string;
    bubbleType: BubbleType;
    textOriginal: string;
    speaker?: string;
    speakerConfidence?: SpeakerConfidence;
    textDirection?: TextDirection;
    lang?: string;
    flags?: ContentFlags;
    bbox: BoundingBox;
}

export interface Panel {
    id: string;
    panelNumber: number;
    bbox: BoundingBox;
    reactionTags: string[];
    flags?: ContentFlags;
    bubbles: Bubble[];
}

/**
 * Page images are keyed by locale.
 * In the delivery model, these are NOT raw origin URLs — they are
 * tokenized delivery URLs generated by the API at request time.
 */
export interface PageImageSet {
    ja?: string;
    en?: string;
    [locale: string]: string | undefined;
}

export interface Page {
    id: string;
    pageNumber: number;
    images: PageImageSet;
    width: number;
    height: number;
    displayRef?: string;
    flags?: ContentFlags;
    panels: Panel[];
}

export interface Episode {
    id: string;
    episodeNumber: number;
    title: string;
    publishedAt: string;
    pages: Page[];
}

export type SeriesStatus = "ongoing" | "completed" | "hiatus";

export interface Series {
    id: string;
    title: string;
    description: string;
    status: SeriesStatus;
    coverUrl: string;
    episodes: Episode[];
}

// ---------------------------------------------------------------------------
// Shareable units (ARCHITECTURE.md §4.2)
// ---------------------------------------------------------------------------

/** A reference to a single bubble for quote sharing. */
export interface QuoteRef {
    seriesId: string;
    episodeId: string;
    pageNumber: number;
    panelNumber: number;
    bubbleNumber: number;
}

/** A reference to a panel range for clip sharing. */
export interface ClipRef {
    seriesId: string;
    episodeId: string;
    pageNumber: number;
    panelStart: number;
    panelEnd: number;
}

// ---------------------------------------------------------------------------
// Entitlement (entitlement-spec.md §3)
// ---------------------------------------------------------------------------

export type EntitlementTargetType =
    | "SERIES"
    | "EPISODE"
    | "VOLUME"
    | "PACK"
    | "BUNDLE";

export type EntitlementSource =
    | "PURCHASE"
    | "CONTRIBUTOR_REWARD"
    | "PROMO"
    | "ADMIN_GRANT"
    | "SUBSCRIPTION";

export type EntitlementStatus = "ACTIVE" | "EXPIRED" | "REVOKED";

// ---------------------------------------------------------------------------
// Pack (ARCHITECTURE.md §8)
// ---------------------------------------------------------------------------

export type PackType =
    | "TRANSLATION"
    | "FOOTNOTE"
    | "COMMENTARY"
    | "LEARNING"
    | "ACCESSIBILITY";

export interface PackSummary {
    id: string;
    type: PackType;
    language?: string;
    version: number;
    title?: string;
    authorLabel?: string;
    isPublished: boolean;
}

// ---------------------------------------------------------------------------
// Locale
// ---------------------------------------------------------------------------

/** Supported locales. Extensible — add new locales as translations arrive. */
export type SupportedLocale = "ja" | "en";

export const DEFAULT_LOCALE: SupportedLocale = "ja";
